name: weather
description: "A new Flutter project."
publish_to: 'none' # Bu proje pub.dev'e yayınlanmayacak

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  image_path: "assets/resim.png"
  macos:
    generate: true
  android: false
  ios: true

